// @flow
export const POKEMONS_REQUESTED = 'POKEMONS_REQUESTED';
export const POKEMONS_SUCCESS = 'POKEMONS_SUCCESS';
export const POKEMONS_FAILURE = 'POKEMONS_FAILURE';

export const DETAILS_REQUESTED = 'DETAILS_REQUESTED';
export const DETAILS_SUCCESS = 'DETAILS_SUCCESS';
export const DETAILS_FAILURE = 'DETAILS_FAILURE';
